# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daylog < Formula
  desc "Takes notes while you work in your editor of choice."
  homepage "https://github.com/notnmeyer/daylog-cli"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.9.0/daylog-cli_Darwin_x86_64.tar.gz"
      sha256 "5b45095fc6ca0ad9c94d977903db7c2f68103aec52c63bcdc6592838dafe7fff"

      define_method(:install) do
        bin.install "daylog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.9.0/daylog-cli_Darwin_arm64.tar.gz"
      sha256 "2ebb97bc271bf07071ba9f6ddd257429bd5005f954cb548ebad15618c783ec51"

      define_method(:install) do
        bin.install "daylog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.9.0/daylog-cli_Linux_x86_64.tar.gz"
      sha256 "df1f52565abeffe5a901e966fcc62ce8aac104d3b38613733a46250507639911"
      define_method(:install) do
        bin.install "daylog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.9.0/daylog-cli_Linux_arm64.tar.gz"
      sha256 "ce7a1ef944741a2584f015957803d7e849e917f33d8f511a0f523876aad52d7d"
      define_method(:install) do
        bin.install "daylog"
      end
    end
  end
end
