# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daylog < Formula
  desc "Takes notes while you work in your editor of choice."
  homepage "https://github.com/notnmeyer/daylog-cli"
  version "0.1.2-1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.1.2-1/daylog-cli_Darwin_arm64.tar.gz"
      sha256 "53897db55f6ca92b31250515420d6e21716025cca65d1fc91659c0fe842e3350"

      def install
        bin.install "daylog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.1.2-1/daylog-cli_Darwin_x86_64.tar.gz"
      sha256 "9ae74759179864cb162e6afddffe49f28aa8bf8911ff929fa142e10cf884936b"

      def install
        bin.install "daylog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.1.2-1/daylog-cli_Linux_arm64.tar.gz"
      sha256 "2808a1c0f7a5f46f91c8e5d649cfe5434ed33d0c97bbe228a08f15f702cb93b4"

      def install
        bin.install "daylog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/notnmeyer/daylog-cli/releases/download/v0.1.2-1/daylog-cli_Linux_x86_64.tar.gz"
      sha256 "aeab7c2845480cfbfd22d9846c29389b3cc4e39e11c91c35f01f5f101f496e77"

      def install
        bin.install "daylog"
      end
    end
  end
end
